import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'ChatGTP Clone',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {apple:'/icon.png'},
  themeColor : '#fff',
}